services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - office-q
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/src/db:/app/src/db
    networks:
      - office-q

networks:
  office-q:
    driver: bridge